# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

u1 = User.create(email: 'example@mail.com', password: '123456', name: 'Tom', bio: "Hi, it's Tom", photo: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1')
u1.confirm


p1 = Post.create(author: u1, title: "My first post", text:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium eaque modi nesciunt animi a officia corporis qui culpa. At nam libero, possimus sapiente modi fuga! Nulla culpa labore eius tempora tempore alias dolore amet, voluptatem modi facilis ullam recusandae pariatur aperiam quam neque? Vitae porro explicabo et delectus repudiandae consequatur corporis, quod cum. Iure tempore aliquid expedita nemo, fugit blanditiis veniam et non aliquam modi cupiditate repudiandae delectus adipisci distinctio magni ipsum necessitatibus voluptates aut inventore illo mollitia id animi quam laboriosam! Earum illum quasi necessitatibus repellendus dolorum doloremque, quis eius velit excepturi accusamus voluptates, fugit, quam magnam est corrupti modi. Magni, perspiciatis repellendus. Dolorum sit debitis molestiae libero ipsam sequi sint voluptatem at. Dignissimos commodi neque vero enim quia in. Odit molestias doloribus perspiciatis vitae totam, autem ratione esse odio tenetur delectus iusto quis optio velit pariatur iure repellat sed aliquid nostrum porro! Minima, deserunt repellat? Explicabo maiores assumenda id. Vel perferendis exercitationem ipsam aut? Totam amet cum quaerat quam nesciunt labore facilis, mollitia est! Atque, iste sint quas consequuntur vel qui asperiores debitis similique impedit officia porro ipsum fugiat in ipsam pariatur excepturi omnis nisi veritatis aliquam tempora quos obcaecati? Facere tempore ab mollitia dolor iure, quae similique!")
p2 = Post.create(author: u1, title: "My second post", text:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium eaque modi nesciunt animi a officia corporis qui culpa. At nam libero, possimus sapiente modi fuga! Nulla culpa labore eius tempora tempore alias dolore amet, voluptatem modi facilis ullam recusandae pariatur aperiam quam neque? Vitae porro explicabo et delectus repudiandae consequatur corporis, quod cum. Iure tempore aliquid expedita nemo, fugit blanditiis veniam et non aliquam modi cupiditate repudiandae delectus adipisci distinctio magni ipsum necessitatibus voluptates aut inventore illo mollitia id animi quam laboriosam! Earum illum quasi necessitatibus repellendus dolorum doloremque, quis eius velit excepturi accusamus voluptates, fugit, quam magnam est corrupti modi. Magni, perspiciatis repellendus. Dolorum sit debitis molestiae libero ipsam sequi sint voluptatem at. Dignissimos commodi neque vero enim quia in. Odit molestias doloribus perspiciatis vitae totam, autem ratione esse odio tenetur delectus iusto quis optio velit pariatur iure repellat sed aliquid nostrum porro! Minima, deserunt repellat? Explicabo maiores assumenda id. Vel perferendis exercitationem ipsam aut? Totam amet cum quaerat quam nesciunt labore facilis, mollitia est! Atque, iste sint quas consequuntur vel qui asperiores debitis similique impedit officia porro ipsum fugiat in ipsam pariatur excepturi omnis nisi veritatis aliquam tempora quos obcaecati? Facere tempore ab mollitia dolor iure, quae similique!")
p3 = Post.create(author: u1, title: "My third post", text:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium eaque modi nesciunt animi a officia corporis qui culpa. At nam libero, possimus sapiente modi fuga! Nulla culpa labore eius tempora tempore alias dolore amet, voluptatem modi facilis ullam recusandae pariatur aperiam quam neque? Vitae porro explicabo et delectus repudiandae consequatur corporis, quod cum. Iure tempore aliquid expedita nemo, fugit blanditiis veniam et non aliquam modi cupiditate repudiandae delectus adipisci distinctio magni ipsum necessitatibus voluptates aut inventore illo mollitia id animi quam laboriosam! Earum illum quasi necessitatibus repellendus dolorum doloremque, quis eius velit excepturi accusamus voluptates, fugit, quam magnam est corrupti modi. Magni, perspiciatis repellendus. Dolorum sit debitis molestiae libero ipsam sequi sint voluptatem at. Dignissimos commodi neque vero enim quia in. Odit molestias doloribus perspiciatis vitae totam, autem ratione esse odio tenetur delectus iusto quis optio velit pariatur iure repellat sed aliquid nostrum porro! Minima, deserunt repellat? Explicabo maiores assumenda id. Vel perferendis exercitationem ipsam aut? Totam amet cum quaerat quam nesciunt labore facilis, mollitia est! Atque, iste sint quas consequuntur vel qui asperiores debitis similique impedit officia porro ipsum fugiat in ipsam pariatur excepturi omnis nisi veritatis aliquam tempora quos obcaecati? Facere tempore ab mollitia dolor iure, quae similique!")
p4 = Post.create(author: u1, title: "My fourth post", text:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium eaque modi nesciunt animi a officia corporis qui culpa. At nam libero, possimus sapiente modi fuga! Nulla culpa labore eius tempora tempore alias dolore amet, voluptatem modi facilis ullam recusandae pariatur aperiam quam neque? Vitae porro explicabo et delectus repudiandae consequatur corporis, quod cum. Iure tempore aliquid expedita nemo, fugit blanditiis veniam et non aliquam modi cupiditate repudiandae delectus adipisci distinctio magni ipsum necessitatibus voluptates aut inventore illo mollitia id animi quam laboriosam! Earum illum quasi necessitatibus repellendus dolorum doloremque, quis eius velit excepturi accusamus voluptates, fugit, quam magnam est corrupti modi. Magni, perspiciatis repellendus. Dolorum sit debitis molestiae libero ipsam sequi sint voluptatem at. Dignissimos commodi neque vero enim quia in. Odit molestias doloribus perspiciatis vitae totam, autem ratione esse odio tenetur delectus iusto quis optio velit pariatur iure repellat sed aliquid nostrum porro! Minima, deserunt repellat? Explicabo maiores assumenda id. Vel perferendis exercitationem ipsam aut? Totam amet cum quaerat quam nesciunt labore facilis, mollitia est! Atque, iste sint quas consequuntur vel qui asperiores debitis similique impedit officia porro ipsum fugiat in ipsam pariatur excepturi omnis nisi veritatis aliquam tempora quos obcaecati? Facere tempore ab mollitia dolor iure, quae similique!")
p5 = Post.create(author: u1, title: "My fifth post", text:"Lorem ipsum dolor sit amet consectetur adipisicing elit. Laudantium eaque modi nesciunt animi a officia corporis qui culpa. At nam libero, possimus sapiente modi fuga! Nulla culpa labore eius tempora tempore alias dolore amet, voluptatem modi facilis ullam recusandae pariatur aperiam quam neque? Vitae porro explicabo et delectus repudiandae consequatur corporis, quod cum. Iure tempore aliquid expedita nemo, fugit blanditiis veniam et non aliquam modi cupiditate repudiandae delectus adipisci distinctio magni ipsum necessitatibus voluptates aut inventore illo mollitia id animi quam laboriosam! Earum illum quasi necessitatibus repellendus dolorum doloremque, quis eius velit excepturi accusamus voluptates, fugit, quam magnam est corrupti modi. Magni, perspiciatis repellendus. Dolorum sit debitis molestiae libero ipsam sequi sint voluptatem at. Dignissimos commodi neque vero enim quia in. Odit molestias doloribus perspiciatis vitae totam, autem ratione esse odio tenetur delectus iusto quis optio velit pariatur iure repellat sed aliquid nostrum porro! Minima, deserunt repellat? Explicabo maiores assumenda id. Vel perferendis exercitationem ipsam aut? Totam amet cum quaerat quam nesciunt labore facilis, mollitia est! Atque, iste sint quas consequuntur vel qui asperiores debitis similique impedit officia porro ipsum fugiat in ipsam pariatur excepturi omnis nisi veritatis aliquam tempora quos obcaecati? Facere tempore ab mollitia dolor iure, quae similique!")


6.times {Comment.create(author: u1, post: p1, text:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae voluptatem ipsam fuga odit quis saepe. Tempora est libero quibusdam vitae doloremque. Consequatur libero commodi recusandae fugit nisi natus et. Vero.")}
4.times {Comment.create(author: u1, post: p2, text:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae voluptatem ipsam fuga odit quis saepe. Tempora est libero quibusdam vitae doloremque. Consequatur libero commodi recusandae fugit nisi natus et. Vero.")}
8.times {Comment.create(author: u1, post: p3, text:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae voluptatem ipsam fuga odit quis saepe. Tempora est libero quibusdam vitae doloremque. Consequatur libero commodi recusandae fugit nisi natus et. Vero.")}
10.times {Comment.create(author: u1, post: p4, text:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae voluptatem ipsam fuga odit quis saepe. Tempora est libero quibusdam vitae doloremque. Consequatur libero commodi recusandae fugit nisi natus et. Vero.")}
3.times {Comment.create(author: u1, post: p5, text:"Lorem ipsum dolor sit, amet consectetur adipisicing elit. Molestiae voluptatem ipsam fuga odit quis saepe. Tempora est libero quibusdam vitae doloremque. Consequatur libero commodi recusandae fugit nisi natus et. Vero.")}

